import re
content = open('new-ui-ux-frontend/pdf-template.html', 'r', encoding='utf-8').read()
content = content.replace('data.latestPosts', '(data.client_metrics ? data.client_metrics.posts : [])')
content = content.replace('data.followersCount', '(data.client_metrics ? data.client_metrics.follower_count : 0)')
content = content.replace('post.likesCount', 'post.likes')
content = content.replace('post.commentsCount', 'post.comments')
content = content.replace('post.productType', 'post.type')
content = content.replace('post.displayUrl', 'post.display_url')
content = content.replace('post.thumbnailUrl', 'post.display_url')
content = content.replace('post.shortCode', 'post.shortcode')
content = content.replace('post.url', 'post.post_url')
content = content.replace('post.timestamp', 'post.date')
open('new-ui-ux-frontend/pdf-template.html', 'w', encoding='utf-8').write(content)
